jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd ~/Desktop/Code/Inventory/Inventory/Inventory  # تعديل المسار ليكون متوافقًا مع macOS
          yarn install
      - name: Build Electron app
        run: |
          cd ~/Desktop/Code/Inventory/Inventory/Inventory  # تعديل المسار ليكون متوافقًا مع macOS
          yarn electron:mac
